# Config file for Gangplank to scrape a local
# Pushgateway (PGW).
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: "pgw"
    honor_labels: true
    static_configs:
      - targets: ["127.0.0.1:9091"]
  - job_name: "alertmanager"
    static_configs:
      - targets: ["127.0.0.1:9093"]
  - job_name: "mnist"
    static_configs:
      - targets: ["127.0.0.1:8561"]
